### ISSUE TITLE
[bug] segfault if a presence server is defined but not available

### ISSUE THREAD

**Issue by source83** [janusvr/janus#56] opened 2019-07-07 01:20 UTC
launching to a room that has a presence server defined in the <room> clause that is not available will cause the native client (linux) to segfault with a large count of the fallowing message:
```
QNativeSocketEngine::write() was not called in QAbstractSocket::ConnectedState
MultiPlayerManager::SocketError():  "Invalid socket descriptor"
```
then crash with:
```
Segmentation fault (core dumped)
```

I have not tried entering said room from a room that had a functioning presence server, so that needs a test too.

**Comment by JamesMcCrae** [comment] 2019-07-07 15:27
Unable to reproduce this bug.  I created a Room as you describe here:

https://vesta.janusvr.com/jamesmccrae/test-broken-custom-presence-server

Then I test with Janus native on Linux (65.0), and get the following output:

```MultiPlayerManager::DoSocketConnect() - tcpsocket trying "no.server.here" 5566 0 ...
url QUrl("ws://no.server.here:5566")
QIODevice::write (QTcpSocket): device not open
MultiPlayerManager::SocketDisconnected()
MultiPlayerManager::SocketDisconnected()
MultiPlayerManager::SocketError():  "Host not found"
MultiPlayerManager::DoSocketConnect() - tcpsocket trying "no.server.here" 5566 1 ...
url QUrl("ws://no.server.here:5566")
MultiPlayerManager::SocketDisconnected()
MultiPlayerManager::DoSocketConnect() - tcpsocket trying "no.server.here" 5566 2 ...
url QUrl("ws://no.server.here:5566")
MultiPlayerManager::SocketDisconnected()
```

The following screenshot shows it not crashing, and the failed connection:

![image](https://user-images.githubusercontent.com/1403837/60770548-0a58ff80-a0aa-11e9-9ecb-6f023a83ebbf.png)

Can you send me the URL you are using?  And confirm you are using the latest 65.0.a753c050 on builds.janusvr.com ?

**Comment by source83** [comment] 2019-07-07 18:08
[https://www.youtube.com/watch?v=RGAe80fPbAE](Video)
and it's the latest commit on github

**Comment by JamesMcCrae** [comment] 2019-07-13 17:54
There was indeed some buggy code related to connection handling, and specifically closing the QWebSocket.  I've since updated things in 65.1, see this commit: 

https://github.com/janusvr/janus/commit/23459e17bc15fdd6c73963dcf91655be2c93b3e4

**Closed by JamesMcCrae** 2019-07-13 17:54 UTC
